services:
  builder:
    image: node:22-alpine
    container_name: node-builder
    working_dir: /app
    volumes:
      - ./output:/output
    command: >
      sh -c "
       (node -v && \
        apk add --no-cache git bash zip && \
        git clone https://github.com/qifi-dev/qrs.git . && \
        npm install -g npm@latest && \
        npm install --global corepack@latest && \
        corepack enable pnpm && \
        pnpm -v && \
        pnpm install && \
        pnpm run generate && \
        mkdir -p /output/qrs && \
        cp -r .output/public/* /output/qrs) 2>&1 | tee /output/build.log;
        cd .output/public && \
        tar -czvf /output/qrs.tar.gz . && \
        zip -r /output/qrs.zip .;
        exit"
    restart: "no"
